-- states
INSERT INTO `states` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'RN','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL);
-- permissions
INSERT INTO `permissions` VALUES (1,'admin','ADMIN','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL),(2,'agent','AGENT','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL);
-- irdas
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'Preocupação dos pais','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (2,'Perda auditiva na família','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (3,'UTI neonatal > 5 dias','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (4,'Hiperbilirrubinemia com transfusão sanguínea','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (5,'Medicamento ototóxico > 5 dias','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (6,'Encefalopatia hipóxica-isquêmica','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (7,'Ventilação mecânica','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (8,'Toxoplasmose','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (9,'Rubéola','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (10,'Citomegalovírus','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (11,'Herpes ','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (12,'Sífilis','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (13,'Zika vírus na gestação','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (14,'Hidrocefalia e/ou microcefalia','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (15,'Síndromes genéticas','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (16,'Sarampo','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (17,'Meningite ','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (18,'Varicela','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (19,'Traumatismo craniano.','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (20,'Quimioterapia','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (21,'Consanguinidade de 1º grau','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (22,'Anóxia perinatal grave','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (23,'Peso ao nascer < 1.500 gramas','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);
INSERT INTO `irdas` (`id`,`irdas`,`created_at`,`updated_at`,`deleted_at`) VALUES (24,'Nascimento pré-termo','2021-01-02 02:48:29','2021-01-02 02:48:29',NULL);

-- questionaries
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'1° dia a 30/31 dias de vida',0,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (2,'1° mês',1,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (3,'2° mês',2,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (4,'3° mês',3,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (5,'4° mês',4,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (6,'5° mês',5,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (7,'6° mês',6,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (8,'7° mês',7,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (9,'8° mês',8,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (10,'9° mês',9,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (11,'10° mês',10,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (12,'11° mês',11,'2020-01-01 00:00:00','2020-01-01 00:00:00',NULL);
INSERT INTO `questionaries` (`id`,`name`,`month_application`,`created_at`,`updated_at`,`deleted_at`) VALUES (13,'12° mês',12,'2021-01-01 00:00:00','2021-01-01 00:00:00',NULL);

-- healthcenters
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'Otomed - Natal','R. Ciro Monteiro, 1187 - Tirol, Natal - RN, 59020-340\nSegunda a sexta das 8:00 as 18:00. Telefone: (84) 3211-1236.','2021-06-20 14:00:09','2021-07-04 17:12:57',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (2,'SUVAG - Natal','Av. Lima e Silva, 966 - Nossa Sra. de Nazaré, Natal - RN, 59062-300. Atendimentos: Segunda a sexta das 7:30 as 16:00. Telefone: (84) 3605-0303.','2021-06-21 13:05:08','2021-07-04 17:18:58',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (3,'CER - Guamaré ','R. Manoel Lucas de Miranda, 6-48, Guamaré - RN, 59598-000\nTelefones: (84) 3525-2383 / (84) 99962-0477','2021-07-04 17:09:22','2021-07-04 17:10:34',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (4,'CER - Pau dos Ferros','AV. da Indepêndencia S/N - Pau dos Ferros / RN - CEP: 59900-000\nTelefone: (84) 3351-2205','2021-07-04 17:10:24','2021-07-04 17:10:24',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (5,'Otocentro - Natal','HC Plaza - R. Cel. Auris Coelho, 285 - 5 andar - Lagoa Nova, Natal - RN, 59075-050\nTelefones: (84) 4009-2000 / (84) 3346-2041','2021-07-04 17:11:35','2021-07-04 17:11:35',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (6,'Centro de Educação e Pesquisa em Saúde Anita Garibaldi (CEPS) - Macaíba','Rod. RN-160, 2010 (KM 1,5 Distrito de, Macaíba - RN, 59280-000. \nAtendimentos: Seg - sex das 08:00 as 17:00\nTelefone: (84) 3271-1064','2021-07-04 17:14:32','2021-07-04 17:14:32',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (7,'Clínica Escola de Fonoaudiologia - UFRN (Natal)','Praia do Meio, Natal - RN.\nAtendimentos: seg - quin 7:30 as 16:00 (marcação) \nTelefone: (84) 3342-9757 ','2021-07-04 17:17:21','2021-07-04 17:17:21',NULL);
INSERT INTO `healthcenters` (`id`,`name`,`description_date`,`created_at`,`updated_at`,`deleted_at`) VALUES (8,'CER - São José de Mipibu',' Av. Pedro Ferreira - Manoel Alves de Souza, São José de Mipibu - RN, 59162-000.\nAtendimentos: seg-sex 08:00 as 17:00\nTelefone: (84)3273-3359','2021-07-04 17:18:25','2021-07-04 17:18:37',NULL);

-- cities
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (1,'NATAL','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (2,'SANTA CRUZ','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (3,'UPANEMA','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (4,'SÃO MIGUEL DO GOSTOSO','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (5,'CAICÓ','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (6,'CURRAIS NOVOS','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (7,'JOÃO CÂMARA','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (8,'GUAMARÉ','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (9,'MACAIBA','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (10,'PAU DOS FERROS','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `cities` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`,`state_id`) VALUES (11,'SÂO JOSE DE MIPIBU','2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);

-- ubs
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (1,'UBS Maria Marlusa','','elizandraupanema@hotmail.com','849991193071','2020-06-16 00:00:00','2021-06-21 12:58:20',3);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (2,'USF Monte Líbano','','usfmlibano2020@gmail.com','84 0 3232-8440','2021-06-21 12:51:34','2021-06-21 12:51:34',1);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (3,'UBS Panatis','Avenida Milton Servita de Brito, 994, Conjunto Panatis, Bairro Potengi.','esfpanatis@gmail.com','','2021-06-21 12:52:44','2021-06-21 12:52:44',1);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (4,'UBS Walfredo Gurgel ','','ubs.walfredogurgel1@gmail.com ','','2021-06-21 12:54:21','2021-06-21 12:54:21',5);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (5,'UBS Itans ','','Jacquelinearaujolucena@gmail.com','','2021-06-21 12:55:21','2021-06-21 12:55:21',5);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (6,'UBS Frei Damião','','','84 9 8636-8399','2021-06-21 12:57:21','2021-06-21 12:57:21',5);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (7,'UBS São Francisco','','','','2021-06-21 12:59:20','2021-06-21 12:59:20',7);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (8,'UBS Cohab','','','','2021-06-21 12:59:50','2021-06-21 12:59:50',7);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (9,'UBS Dr. Naelson','','','','2021-06-21 13:00:12','2021-06-21 13:00:12',3);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (10,'UBS Silvio Bezerra de Melo','','ubssilviobezerra@gmail.com','','2021-06-21 13:01:18','2021-06-21 13:01:18',6);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (11,'UBS Marlene Ricardo','','unidadebasica2@gmail.com','','2021-06-21 13:02:13','2021-06-21 13:02:13',6);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (12,'UBS Maceió','','','','2021-06-21 13:02:31','2021-06-21 13:02:31',4);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (13,'UBS Morros','','','','2021-06-21 13:02:45','2021-06-21 13:02:45',4);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (14,'UBS Serra Verde','','','','2021-06-21 13:03:00','2021-06-21 13:03:00',4);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (15,'UBS Dourados','','','','2021-06-21 13:03:12','2021-06-21 13:03:12',4);
INSERT INTO `ubs` (`id`,`name`,`street`,`email`,`telefone`,`created_at`,`updated_at`,`city_id`) VALUES (16,'UBS Paraíso 2','','','','2021-06-21 13:03:25','2021-07-04 17:03:13',2);

-- question_questionaries
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (1,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,1);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (2,'Seu filho assusta com sons fortes?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,1);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (3,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,2);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (4,'Seu filho assusta com sons fortes?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,2);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (5,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,3);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (6,'Seu filho presta atenção ao som?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,3);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (7,'Seu filho reconhece a sua voz?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,3);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (8,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,4);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (9,'Seu filho acalma com sua voz, com música de ninar?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,4);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (10,'Seu filho fala vogais como a, u?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,4);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (11,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,5);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (12,'Seu filho tenta virar a cabeça procurando o som?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,5);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (13,'Seu filho fala mais sons que no mês anterior, por exemplo, como fff, oooo ?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,5);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (14,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,6);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (15,'Seu filho procura os sons?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,6);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (16,'Fala vários sons como se quisesse conversar?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,6);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (17,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,7);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (18,'Seu filho olha quando você chama?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,7);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (19,'Fala bababa, mamama querendo conversar?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,7);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (20,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,8);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (21,'Seu filho reconhece alguns nomes da família?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,8);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (22,'Seu filho fala várias sílabas diferentes? Por exemplo: dada, papa.','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,8);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (23,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,9);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (24,'Vira rapidamente quando chamam?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,9);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (25,'Gosta de brincar com brinquedos que fazem barulhos?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,9);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (26,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,10);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (27,'Compreende quando falam “não”?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,10);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (28,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,11);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (29,'Tenta imitar os sons que fazem para ele?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,11);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (30,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,12);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (31,'Dá tchau quando ouve alguém falar tchau?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,12);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (32,'Fala enrolado como se estivesse conversando?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,12);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (33,'Seu filho ouve bem?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,13);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (34,'Fala as primeiras palavras?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,13);
INSERT INTO `question_questionaries` (`id`,`question`,`created_at`,`updated_at`,`deleted_at`,`questionary_id`) VALUES (35,'Entende ordens como “cadê” e “dá”?','2020-01-01 00:00:00','2020-01-01 00:00:00',NULL,13);


-- users
INSERT INTO `users` (`id`,`name`,`email`,`cpf`,`password`,`phone`,`active`,`created_at`,`updated_at`,`deleted_at`,`permission_id`) VALUES (1,'Alice Andrade','aliceandr25@gmail.com ','112.184.274-77','123','84 9 88402510',1,'2020-06-16 00:00:00','2020-06-16 00:00:00',NULL,1);
INSERT INTO `users` (`id`,`name`,`email`,`cpf`,`password`,`phone`,`active`,`created_at`,`updated_at`,`deleted_at`,`permission_id`) VALUES (2,'Frankleiton','frankleiton@gmail.com','107.062.634-13','123','84 9 9119-3071',1,'2021-06-19 16:53:46','2021-07-03 20:33:56',NULL,1);
INSERT INTO `users` (`id`,`name`,`email`,`cpf`,`password`,`phone`,`active`,`created_at`,`updated_at`,`deleted_at`,`permission_id`) VALUES (3,'Agente Teste','agente@email.com','111.222.333-44','123','84 9 9119-3071',1,'2021-06-19 16:53:46','2021-07-03 20:33:56',NULL,2);


-- agents
INSERT INTO `agents` (`id`,`number_a_c_s`,`profile_photo`,`created_at`,`updated_at`,`deleted_at`,`user_id`,`ub_id`) VALUES (1,'13457',NULL,'2021-06-19 16:53:46','2021-06-19 16:53:46',NULL,3,1);

-- brainfits
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'Criança com 4 anos, família relata que ela não fala nenhuma palavra e nem reage para os sons. Portanto, deve ser encaminhada para avaliação audiológica completa. ',1,'Aos 4 anos é esperado que a criança fale quase todos os fonemas da língua e já forme frases complexas. Pode ser uma perda auditiva! Para mais informações: Aba dos marcos do desenvolvimento','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (2,'Durante a visita domiciliar ao perceber que o aparelho auditivo de uma criança está apitando, a conduta deve ser: encaminhá-la imediatamente para o serviço de saúde auditiva mais próximo para refazer os exames e adquirir um novo aparelho.',0,' Lembre-se há alguns problemas simples que você poderia auxiliar, como por exemplo a limpeza e adequada colocação do molde. Caso verifique que o molde precisa ser trocado, então encaminhe. Para mais informações: Aba das Dúvidas Frequentes.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (3,'Criança de 3 anos, não consegue escutar sons fracos e não localiza os sons, mas obteve resultado “passa” na triagem auditiva neonatal. Nesse caso, não é preciso encaminhar para uma avaliação audiológica completa.',0,'Lembre-se: existem perdas auditivas que são adquiridas. Mesmo com resultado normal na triagem auditiva, a criança pode vir a apresentar perda auditiva. Sempre que os pais informarem que a criança não ouve bem, encaminhe. Para mais informações: Aba de Duvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (4,'Criança com 2 anos de idade, você verificou que ela não realizou a triagem auditiva neonatal, mas a família não tem queixa quanto a audição e a criança está desenvolvendo a linguagem adequadamente. Neste caso, não será necessário encaminhar para avaliação audiológica.',1,'Como a criança está se desenvolvendo dentro do esperado, a conduta correta será acompanhar. O encaminhamento para o serviço de saúde auditiva deverá ocorrer somente se a família apresentar queixas ou for constatado atraso no desenvolvimento. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (5,' A maneira correta de limpar a orelha é com o cotonete.',0,'A cera não é sujeira, ela é proteção! Lembre-se que a orelha possui um sistema autolimpante, a forma correta de limpar o excesso de cerúmen que fica no pavilhão auricular é com uma toalha úmida após o banho. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (6,'Crianças que apresentam deficiência auditiva de grau profundo têm possibilidade de adquirir a linguagem oral caso o diagnóstico e a intervenção sejam precoces.',1,'A possibilidade de desenvolver a linguagem em crianças com perda auditiva está totalmente ligada ao tempo que ela fica sem ouvir. O diagnóstico e o início do tratamento o mais rápido possível é fundamental. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (7,'A família refere que a criança de 10 meses não balbucia e nem busca os sons. Você verifica na caderneta de saúde que ela “passou” na triagem auditiva neonatal e que no mês anterior havia registrado resposta “não” no questionário de acompanhamento. A conduta neste caso será esperar a próxima visita, pois o desenvolvimento está adequado para a idade.',0,'Lembre-se: sempre que a criança tiver desempenho aquém do esperado em dois meses seguidos, é importante encaminhar para avaliação audiológica, independentemente do resultado da triagem auditiva! Para mais informações: Aba de Revisão; Marcos do desenvolvimento da audição e da linguagem;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (8,' Criança de 6 anos com dificuldades escolares, diz não ouvir a professora e tem trocas na fala que não foram superadas com a idade. Pode ser um caso de perda auditiva de grau leve ou moderado, merece investigação!',1,'A perda auditiva de grau leve ou moderado pode ser detectada nessa idade justamente porque a criança consegue ouvir os sons de média e forte intensidade e por isso não foi notado antes pela família. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (9,'É normal crianças com 4 meses de vida não se assustarem com sons fortes, não reagir à voz dos pais e não ter atenção aos sons ambientais. Só se torna preocupante depois do primeiro ano de vida.',0,'Aos 4 meses a criança já deve reagir demonstrando atenção aos sons de fala e ambientais e pode se assustar com sons fortes. Para mais informações: Aba dos Marcos do Desenvolvimento da audição;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (10,'A família está preocupada com a audição da criança de 12 meses por relatarem que às vezes ela responde ao som e outras vezes não. Esta criança deverá ser encaminhada para avaliação audiológica imediata.',1,'Algumas perdas auditivas têm como característica a flutuação na audição, ou seja, em alguns momentos escutam melhor e em outros pior. A avaliação audiológica é muito importante para definir a existência ou não de perda auditiva. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (11,'Analisando a Caderneta de Saúde de uma criança de 3 meses de idade, foi visto que ela obteve resultado “normal” na triagem auditiva neonatal e não possui indicadores de risco para deficiência auditiva, sendo assim, não é necessário a aplicação do questionário do desenvolvimento da audição e linguagem. ',0,'Lembre-se: existem perdas auditivas adquiridas na infância ou que se manifestam depois do nascimento mesmo quando não há indicadores de risco, portanto, é importante acompanhar o desenvolvimento da audição e da linguagem de todas as crianças. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (12,'Aplicando o questionário de desenvolvimento de audição e linguagem, você percebe que foram obtidas respostas “NÃO” nas duas últimas aplicações. Com isso, a criança deve ser encaminhada para os Serviços de saúde auditiva para a realização da avaliação audiológica.',1,'Se no acompanhamento da criança são obtidas respostas “NÃO” no questionário dois meses consecutivos, esta criança deve ser encaminhada para a realização da avaliação audiológica imediata. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (13,'Para crianças com perda auditiva sensorioneural de grau moderado, severo ou profundo a utilização do aparelho auditivo ou implante coclear é essencial para que seja possível o desenvolvimento da linguagem oral.',1,'O uso dos dispositivos (aparelho auditivo ou implante) é importante para que a criança escute todos os sons de fala e assim tenha condições de adquirir a linguagem oral. O uso do aparelho auditivo ou implante coclear e a terapia fonoaudiológica são fundamentais para o desenvolvimento da criança. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (14,'Deve-se priorizar o acompanhamento do desenvolvimento da audição e da linguagem de crianças que possuem indicadores de risco para a deficiência auditiva ou que não fizeram a triagem auditiva neonatal.',0,'O acompanhamento do desenvolvimento da audição e linguagem deve ser realizado com todas as crianças dentro da área de cobertura, pois, crianças sem risco ou com resultado normal na triagem auditiva também podem vir a apresentar perda auditiva. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (15,'Após um tempo de uso do AASI, a família de uma criança relata que o aparelho dela está com algum problema e você percebe algumas fissuras no molde. É importante orientar a família que um novo molde deve ser feito, encaminhando-a ao Serviço de Saúde Auditiva ou o CER.',1,'Ao verificar que o problema não está relacionado somente à colocação adequada do molde na orelha, ou ainda, à limpeza e controle de volume, a família deve ser orientada a buscar o Serviço de Saúde Auditiva que a criança recebeu o aparelho. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (16,'A família de uma criança informa que ela tem usado o aparelho auditivo e por isso não precisa levá-la à terapia fonoaudiológica. Você deve orientar que comparecer nas sessões de terapia é fundamental para que a criança consiga desenvolver as habilidades auditivas e de linguagem.',1,'Após começar o uso do aparelho auditivo ou implante coclear, a criança deve comparecer às sessões de terapia fonoaudiológica para “aprender a ouvir” e propiciar a aquisição da linguagem oral! Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (17,'Iniciando a terapia fonoaudiológica e utilizando o aparelho auditivo, a família não precisa estimular a linguagem da criança em casa, tendo em vista que a terapia é feita com profissionais que exercem esse papel durante as sessões semanais.',0,'Mesmo comparecendo frequentemente à terapia fonoaudiológica, a estimulação dada pela família é uma peça fundamental no desenvolvimento das habilidades auditivas e de linguagem da criança. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (18,'Criança de 2 meses idade obteve o resultado “falha” em uma das orelhas na triagem auditiva. Você deve informar à família que a criança possui uma perda auditiva e que é necessário o uso de aparelho auditivo para que seja possível o desenvolvimento da linguagem. ',0,'O resultado da triagem não define o diagnóstico audiológico da criança, sendo necessária uma avaliação audiológica completa para definir o diagnóstico, e se necessário, iniciar o tratamento. Esta criança deve ser encaminhada imediatamente para avaliação. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (19,'Criança com 8 meses de idade, a família acha que ela não escuta bem. O encaminhamento para avaliação auditiva deverá ocorrer no próximo mês, caso mantenha a resposta “não” no questionário de acompanhamento.',0,'Para a questão “seu filho ouve bem?” mediante a obtenção da primeira resposta “não” já deve-se encaminhar a criança para avaliação audiológica imediata. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (20,'Com um certo tempo de uso do AASI, a família da criança relata que ela tem apresentado algumas reclamações sobre estar ouvindo o som de forma cortada. Você deve orientar a família à procurar de imediato o Serviço de Saúde Auditiva para solucionar o problema.',0,'No caso apresentado, uma possível causa para essas interrupções no som é a necessidade de limpeza nos contatos da bateria, o que pode ser resolvido facilmente. Se a limpeza não resolver, aí sim deve orientar a família a buscar o Serviço de Saúde Auditiva em que recebeu o dispositivo. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (21,'Rubéola congênita e Meningite bacteriana são considerados indicadores de risco para deficiência auditiva e podem ser prevenidos com orientação à população e adequada imunização.',1,'Dentre os diversos indicadores de risco, a rubéola congênita e a meningite bacteriana são dois exemplos que podem ser prevenidos orientando a população quanto a importância da imunização. Lembre-se outras doenças podem estar associadas à perda auditiva como Sífilis e Citomegalovírus. Para mais informações: Aba dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (22,'Quando uma criança possui resultado “normal” na Triagem Auditiva Neonatal, significa que ela não terá perda auditiva.',0,'A triagem auditiva não exclui a possibilidade da criança adquirir uma perda posteriormente, ou ainda, ela pode ter uma perda auditiva por alteração em alguma estrutura não avaliada pelo teste realizado na maternidade. Para mais informações: Aba dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (23,'Uma das causas mais comuns de perda auditiva do tipo condutiva é a rolha de cera e em alguns casos ela pode ser evitada apenas com a limpeza correta da orelha. ',1,'A rolha de cera pode ser causada pelo uso do cotonete, que ao contrário do que se pensa, não limpa a orelha. O cotonete acaba empurrando a cera e formando uma rolha rígida que impede a passagem livre do som. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (24,'Crianças cujos pais apresentam deficiência auditiva também apresentarão deficiência auditiva por causa genética.',0,'O histórico de deficiência auditiva na família implica em um indicador de risco, mas não significa que necessariamente a criança apresentará perda auditiva. É fundamental o acompanhamento na atenção primária e o encaminhamento para avaliação quando necessário. Para mais informações: Aba de Revisão; Fluxograma da TAN;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (25,'Criança de 9 meses recebeu diagnóstico de perda auditiva mas não está utilizando o aparelho auditivo porque a família tem resistência. O profissional da atenção primária pode auxiliar reforçando a importância do uso contínuo do aparelho auditivo para o desenvolvimento da linguagem.',1,'A conscientização da família é importante para a aceitação do uso do aparelho auditivo pela criança. A família é peça fundamental na reabilitação auditiva e as orientações contínuas favorecem essa adesão ao tratamento. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (26,'Criança de 2 anos de idade é diagnosticada com perda auditiva condutiva. Sua família relata que ela ainda fala poucas palavras e apenas as pessoas que convivem com ela, conseguem entender. Por se tratar de uma perda auditiva condutiva, não é necessário preocupação.',0,'Mesmo sabendo que algumas perdas auditivas condutivas se recuperam espontaneamente, o tratamento adequado é de extrema importância para a saúde auditiva da criança. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (27,'Algumas intercorrências no período pré, peri e pós-natal podem influenciar na saúde auditiva da criança, sendo considerados indicadores de risco para a deficiência auditiva. O adequado pré-natal pode prevenir perda auditiva.',1,'Cerca de 60% das causas de perdas auditivas são evitáveis e o pré-natal é peça chave para auxiliar na prevenção destas infecções. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (28,'O desenvolvimento auditivo possui padrões diferentes para cada faixa etária. Virar a cabeça para localizar o som apresentado ao seu lado é um comportamento esperado para crianças acima de um ano.',0,'Por volta dos 3 meses de idade, o bebê já deve começar a voltar a cabeça levemente quando escuta algum som e aos 6 meses a habilidade de localização lateral já deve estar adquirida. Para mais informações: Aba de marcos do desenvolvimento da audição.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (29,'Criança possui 9 meses de idade, apresenta indicadores de risco para deficiência auditiva, mas obteve resultado “normal” na triagem auditiva. Ao ser questionado pela família se a criança precisa fazer alguma avaliação audiológica adicional, você deve responder que não há necessidade.',0,'Para crianças que apresentam indicadores de risco para deficiência auditiva, mesmo com resultado normal na triagem auditiva é indicado a realização de uma avaliação audiológica completa para monitoramento. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (30,'Ao se deparar com queixas relacionadas ao aparelho auditivo estar “mudo”, você precisa orientar a família a procurar imediatamente o Serviço de Saúde Auditiva, pois o aparelho está quebrado.',0,'Inicialmente, você deve observar se o aparelho está realmente ligado, com problemas no posicionamento da pilha ou até mesmo, se a pilha acabou. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (31,'Criança com 3 anos, família relata que ela não fala nenhuma palavra e nem reage para os sons. Portanto, deve ser encaminhada para avaliação audiológica completa.',1,'Aos 3 anos é esperado que a criança fale quase todos os fonemas da língua e já forme frases com sentido. Pode ser uma perda auditiva! Para mais informações: Aba dos marcos do desenvolvimento','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (32,'Durante a visita domiciliar ao perceber que o aparelho auditivo de uma criança está apitando, você deve: verificar se o molde está bem encaixado ou sujo e só encaminhá-la para o serviço de saúde auditiva se perceber que o molde precisa ser trocado.',1,'Há alguns problemas simples que você poderia auxiliar, como por exemplo a limpeza e adequada colocação do molde. Caso verifique que o molde precisa ser trocado, então encaminhe. Para mais informações: Aba das dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (33,'Criança de 2 anos, não consegue escutar sons fracos e não localiza os sons, mas obteve resultado “passa” na triagem auditiva neonatal. Nesse caso, não é preciso encaminhar para uma avaliação audiológica completa.',0,'Existem perdas auditivas que são adquiridas. Mesmo com resultado normal na triagem auditiva, a criança pode vir a apresentar perda auditiva. Sempre que os pais informarem que a criança não ouve bem, encaminhe. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (34,'Criança, 6 meses de idade, você verificou que ela não realizou a triagem auditiva neonatal, mas a família não tem queixa quanto a audição ou com a linguagem. Neste caso, não será necessário encaminhar para avaliação audiológica.',1,'encaminhamento para o serviço de saúde auditiva deverá ocorrer somente se a família apresentar queixas ou for constatado atraso no desenvolvimento por meio do questionário de acompanhamento. Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (35,'A maneira correta de limpar a orelha é com uma toalha úmida após o banho.',1,'A cera não é sujeira, ela é proteção! Lembre-se que a orelha possui um sistema autolimpante, a forma correta de limpar o excesso de cerúmen que fica no pavilhão auricular é com uma toalha úmida após o banho. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (36,'Crianças que apresentam deficiência auditiva de grau profundo não têm possibilidade de adquirir a linguagem oral mesmo se o diagnóstico e a intervenção forem precoces.',0,'A possibilidade de desenvolver a linguagem em crianças com perda auditiva está totalmente ligada ao tempo que ela fica sem ouvir. O diagnóstico e o início do tratamento o mais rápido possível é fundamental. Para mais informações: Aba de dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (37,'Criança,11 meses, não balbucia e não tenta imitar os sons que fazem para ela. Tem resultado “passa” na triagem auditiva neonatal, mas no mês anterior já havia registrado resposta “não” no questionário de acompanhamento. Você deverá encaminhá-la para avaliação auditiva já que ela falhou 2 meses consecutivos no questionário.',1,'Lembre-se: sempre que a criança tiver desempenho aquém do esperado em dois meses seguidos, é importante encaminhar para avaliação audiológica, independentemente do resultado da triagem auditiva! Para mais informações: Aba Marcos','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (38,'Criança de 7 anos com dificuldades escolares, diz não ouvir a professora e tem trocas na fala que não foram superadas com a idade. Não há suspeitas de perda auditiva, já que ela conseguiu aprender a falar mesmo que trocando algumas letras.',0,'A perda auditiva de grau leve ou moderado pode ser detectada nessa idade justamente porque a criança consegue ouvir os sons de média e forte intensidade e por isso não foi notado antes pela família. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (39,'Não é normal que crianças com 4 meses de vida não se assustem com sons fortes, não reajam à voz dos pais e não prestem atenção aos sons ambientais.',1,'Aos 4 meses a criança já deve reagir demonstrando atenção aos sons de fala e ambientais e pode se assustar com sons fortes. Para mais informações: Aba dos Marcos do Desenvolvimento da audição;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (40,'A família está preocupada com a audição da criança de 7 meses por relatarem que às vezes ela responde ao som e outras vezes não. Esta criança deverá ser encaminhada para avaliação audiológica imediata.',1,'Algumas perdas auditivas têm como característica a flutuação na audição, ou seja, em alguns momentos escutam melhor e em outros pior. A avaliação audiológica é muito importante para definir a existência ou não de perda auditiva. ','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (41,'Criança de 3 meses de idade, possui indicadores de risco para deficiência auditiva mas obteve resultado “normal” na triagem auditiva neonatal, sendo assim, não é necessário a aplicação do questionário do desenvolvimento da audição e linguagem.',0,'Lembre-se: existem perdas auditivas adquiridas na infância ou que se manifestam depois do nascimento especialmente quando há indicadores de risco, portanto, é importante acompanhar o desenvolvimento da audição e da linguagem de todas as crianças. ','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (42,'Você percebe que foram obtidas respostas “NÃO” nas duas últimas aplicações do questionário de acompanhamento em uma criança de sua cobertura. Apesar disso, ela ainda não deve ser encaminhada para os Serviços de saúde auditiva.',0,'Se no acompanhamento da criança são obtidas respostas “NÃO” no questionário dois meses consecutivos, esta criança deve ser encaminhada para a realização da avaliação audiológica imediata. Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (43,'Para crianças com perda auditiva sensorioneural de grau moderado, severo ou profundo a utilização do aparelho auditivo ou implante coclear não influencia no desenvolvimento da linguagem oral.',0,'O uso do aparelho auditivo ou implante coclear e a terapia fonoaudiológica são fundamentais para o desenvolvimento da criança. Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (44,' Não deve-se priorizar o acompanhamento do desenvolvimento da audição e da linguagem de crianças que possuem indicadores de risco para a deficiência auditiva ou que não fizeram a triagem auditiva neonatal. O acompanhamento é para todas as crianças, com ou sem risco.',1,'O acompanhamento do desenvolvimento da audição e linguagem deve ser realizado com todas as crianças dentro da área de cobertura, pois, crianças sem risco ou com resultado normal na triagem auditiva também podem vir a apresentar perda auditiva.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (45,'Após um tempo de uso do AASI, a família de uma criança relata que o aparelho dela está com algum problema e você percebe algumas fissuras no molde. É dispensável orientar a família que um novo molde deve ser feito.',0,'Ao verificar que o problema não está relacionado somente à colocação adequada do molde na orelha, ou ainda, à limpeza e controle de volume, a família deve ser orientada a buscar o Serviço de Saúde Auditiva que a criança recebeu o aparelho. ','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (46,'A família de uma criança informa que ela tem usado o aparelho auditivo e por isso não precisa levá-la à terapia fonoaudiológica. A conduta da família, que está correta, uma vez que utilizando o aparelho auditivo a criança não precisa de terapia para conseguir ouvir os sons.',0,'Após começar o uso do aparelho auditivo ou implante coclear, a criança deve comparecer às sessões de terapia fonoaudiológica para “aprender a ouvir” e propiciar a aquisição da linguagem oral! Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (47,'Iniciando a terapia fonoaudiológica e utilizando o aparelho auditivo, é importante que a família estimule a linguagem da criança também em casa, tendo em vista que a terapia é feita com profissionais que exercem esse papel durante as sessões semanais.',1,'Mesmo comparecendo frequentemente à terapia fonoaudiológica, a estimulação dada pela família é uma peça fundamental no desenvolvimento das habilidades auditivas e de linguagem da criança. Para mais informações: Aba de Dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (48,'Criança, 1 ano, obteve o resultado “falha” nas duas orelhas na triagem auditiva. Você deve informar à família que a criança possui uma perda auditiva e que é necessário o uso de aparelho auditivo para que seja possível o desenvolvimento da linguagem.',0,'A triagem não define se a criança tem ou não perda auditiva, sendo necessária uma avaliação audiológica completa para definir o diagnóstico, e se necessário, iniciar o tratamento. Esta criança deve ser encaminhada imediatamente para avaliação. Para mais informações: Aba de Dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (49,'Criança com 8 meses de idade, a família acha que ela não escuta bem. O encaminhamento para avaliação auditiva deverá ocorrer imediatamente.',1,'Para a questão “seu filho ouve bem?” mediante a obtenção da primeira resposta “não” já deve-se encaminhar a criança para avaliação audiológica imediata. Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (50,'Família de criança usuária de aparelho auditivo relata que ela vem apresentando  reclamações sobre estar ouvindo o som de forma “cortada”. Você poderá checar se os contatos da bateria estão limpos e se a limpeza não resolver, encaminhar a criança para o Serviço de Saúde em que ela recebeu o dispositivo. ',1,'No caso apresentado, uma possível causa para essas interrupções no som é a necessidade de limpeza nos contatos da bateria, o que pode ser resolvido facilmente. Se a limpeza não resolver, aí sim deve orientar a família a buscar o Serviço de Saúde','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (51,'Rubéola congênita e Meningite bacteriana são considerados indicadores de risco para deficiência auditiva e NÃO podem ser prevenidos com orientação à população e adequada imunização.',0,'Dentre os diversos indicadores de risco, a rubéola congênita e a meningite bacteriana são dois exemplos que podem ser prevenidos orientando a população quanto a importância da imunização. Outras doenças podem estar associadas à perda auditiva como Sífilis e Citomegalovírus. Para mais informações: Aba Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (52,'Quando uma criança possui resultado “normal” na Triagem Auditiva Neonatal, não significa que ela não terá perda auditiva, já que triagem auditiva não exclui a possibilidade da criança adquirir uma perda posteriormente',1,'A triagem auditiva não exclui a possibilidade da criança adquirir uma perda posteriormente, ou ainda, ela pode ter uma perda auditiva por alteração em alguma estrutura não avaliada pelo teste realizado na maternidade. Para mais informações: Aba dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (53,'Uma das causas mais comuns de perda auditiva do tipo condutiva é a rolha de cera, que infelizmente não pode ser evitada de forma alguma.',0,'A rolha de cera pode ser causada pelo uso do cotonete, que ao contrário do que se pensa, não limpa a orelha. O cotonete acaba empurrando a cera e formando uma rolha rígida que impede a passagem livre do som. Para mais informações: Aba de Dúvidas','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (54,'Crianças cujos pais apresentam deficiência auditiva não necessariamente apresentarão deficiência auditiva.',1,'O histórico de deficiência auditiva na família implica em um indicador de risco, mas não significa que a criança apresentará perda auditiva. É fundamental o acompanhamento na atenção primária e o encaminhamento para avaliação quando necessário. Para mais informações: Aba de Dúvidas;','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (55,'Criança de 9 meses recebeu diagnóstico de perda auditiva mas não está utilizando o aparelho auditivo porque a família tem resistência. O profissional da atenção primária não pode auxiliar nesses casos.',0,' Você pode auxiliar reforçando a importância do uso contínuo do aparelho auditivo para o desenvolvimento da linguagem. A família é peça fundamental na reabilitação auditiva e as orientações contínuas favorecem essa adesão ao tratamento. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (56,'Criança de 3 anos de idade é diagnosticada com perda auditiva condutiva. Sua família relata que ela ainda fala poucas palavras e poucas pessoas conseguem entendê-la. Por se tratar de uma perda auditiva condutiva, não é necessário preocupação.',0,'Mesmo sabendo que algumas perdas auditivas condutivas se recuperam espontaneamente, o tratamento adequado é de extrema importância para a saúde auditiva da criança. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (57,'Algumas intercorrências no período pré, peri e pós-natal podem influenciar na saúde auditiva da criança, sendo considerados indicadores de risco para a deficiência auditiva. Porém, mesmo com o adequado pré-natal, não é possível prevenir perda auditiva. ',0,'Cerca de 60% das causas de perdas auditivas são evitáveis e o pré-natal é peça chave para auxiliar na prevenção destas infecções. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (58,'O desenvolvimento auditivo possui padrões diferentes para cada faixa etária. Virar a cabeça para localizar o som apresentado ao seu lado é um comportamento esperado para crianças acima de 6 meses.',1,'Por volta dos 3 meses de idade, o bebê já deve começar a voltar a cabeça levemente quando escuta algum som e aos 6 meses a habilidade de localização lateral já deve estar adquirida. Para mais informações: Aba de marcos do desenvolvimento','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (59,'Criança, 9 meses, apresenta indicadores de risco para deficiência auditiva, mas obteve resultado “passa” na triagem auditiva. A família te questiona se a criança precisa fazer alguma avaliação audiológica adicional. Sua resposta deve ser que SIM. ',1,'Para crianças que apresentam indicadores de risco para deficiência auditiva, mesmo com resultado normal na triagem auditiva é indicado a realização de uma avaliação audiológica completa para monitoramento. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
INSERT INTO `brainfits` (`id`,`confirmation`,`afirmation`,`justification`,`created_at`,`updated_at`,`deleted_at`) VALUES (60,'Ao se deparar com queixas relacionadas ao aparelho auditivo estar “mudo”, você precisa inicialmente verificar se o aparelho está realmente ligado antes de fazer qualquer encaminhamento para o Serviço de Saúde Auditiva.',1,'Inicialmente, você deve observar se o aparelho está realmente ligado, com problemas no posicionamento da pilha ou até mesmo, se a pilha acabou. Para mais informações: Aba de Dúvidas.','2021-05-11 00:00:00','2021-05-11 00:00:00',NULL);
